version: '2'

services:
  app:
    image: 'bulletin:latest'
    build:
      context: .
      dockerfile: Dockerfile.local
    ports:
      - ${PORT}:8080
    container_name: app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=${SPRING_JPA_HIBERNATE_DDL_AUTO}
      - SPRING_JPA_DATABASE-PLATFORM=${SPRING_JPA_DATABASE-PLATFORM}
      - ADMIN_ACCESS_TOKEN=${ADMIN_ACCESS_TOKEN}
      - S3_SECRET_KEY=${S3_SECRET_KEY}
      - S3_ACCESS_KEY_ID=${S3_ACCESS_KEY_ID}
          
  db:
    image: 'postgres:13.1-alpine'
    container_name: bulletin-db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  
